[package]
name = "worldbase-docs"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
calamine = { workspace = true }
lopdf = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
